theme: jekyll-theme-minimal
title: Desktop Goose's Resource Hub
description: An unofficial place to share your mods, etc. PRs and stars are appreciated!
logo: https://desktopgooseunofficial.github.io/ResourceHub/assets/images/banner.png
show_downloads: false
google_analytics: G-NBH9YW8R23
